#!/bin/bash

# This script will add the CyberLynk VoIP team ssh keys to your server
# Running this script will allow members of the CyberLynk VoIP team to access your server

# To Remove these keys run "sed -i '/clspprt/d' /root/.ssh/authorized_keys"

# Get the key list
curl https://raw.githubusercontent.com/CyberLynk/freepbxhosting_resources/main/keylist > /tmp/keylist
 
# Check to make sure the key list isn't a 404 error
if [[ $(wc -l </tmp/keylist) -ge 2 ]]
   
  # If everything looks good copy away, otherwise terminate
  then
    mkdir -p /root/.ssh
    touch /root/.ssh/authorized_keys
    sed -i '/clspprt/d' ~/.ssh/authorized_keys 
    cat /tmp/keylist >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    chmod 700 /root/.ssh
fi
